#!/usr/bin/env bash
#
# Build an archiso
set -e
readonly conf='/baseline'
readonly path='/docker'
readonly iso='/out/archiso-v-x86_64.iso'

pacman -Sy archiso --noconfirm --disable-sandbox
name="ARCHISO-v$(date '+%d%m%y')"

cd /
cp -R "/usr/share/archiso/configs${conf}" /
mkdir -p "${conf}/airootfs/etc/"{sysctl.d,xdg/reflector,udev/rules.d}
mkdir -p "${conf}/airootfs/etc/systemd/timesyncd.conf.d"
mkdir -p "${conf}/airootfs/usr/local/bin"

cp "${path}/packages.x86_64" "${conf}"
cp "${path}/25-wireless.network" "${conf}/airootfs/etc/systemd/network"
cp "${path}/60-io.rules" "${conf}/airootfs/etc/udev/rules.d"
cp "${path}/99-sysctl.conf" "${conf}/airootfs/etc/sysctl.d"
cp "${path}/ntp.conf" "${conf}/airootfs/etc/systemd/timesyncd.conf.d"
cp "${path}/reflector.conf" "${conf}/airootfs/etc/xdg/reflector"
cp "${path}/arch-install" "${conf}/airootfs/usr/local/bin"

sed "s/NAME/${name}/" "${path}/profiledef.sh" > "${conf}/profiledef.sh"
cat "${path}/20-wired.network" \
  > "${conf}/airootfs/etc/systemd/network/20-ethernet.network"
cat "${path}/dns.conf" \
  > "${conf}/airootfs/etc/systemd/resolved.conf.d/archiso.conf"
cat "${path}/arch-zen.conf" \
  > "${conf}/efiboot/loader/entries/01-archiso-x86_64-linux.conf"
cat "${path}/linux.preset" \
  > "${conf}/airootfs/etc/mkinitcpio.d/linux-zen.preset"
cat "${path}/pacman.conf" \
  > "${conf}/pacman.conf"

echo "$name" \
  > "${conf}/airootfs/etc/hostname"
echo 'editor no' \
  > "${conf}/efiboot/loader/loader.conf"
echo 'root:x:0:0:root:/root:/usr/bin/bash' \
  > "${conf}/airootfs/etc/passwd"
echo 'root::1::::::' \
  > "${conf}/airootfs/etc/shadow"

echo '- Building archiso...'
mkarchiso "${conf}"
echo '- FUCKING WONDERHOY'
ls -lh "${iso}"
file "${iso}"
