#!/usr/bin/env bash
#
# Build an archiso
set -e
readonly conf='/baseline'
readonly path='/docker'

cat "${path}/pacman.conf" > /etc/pacman.conf
pacman -Sy archiso --noconfirm
name="ARCHISO-v$(date '+%d%m%y')"

cd /
cp -R "/usr/share/archiso/configs${conf}" /
mkdir -p "${conf}/airootfs/etc/"{sysctl.d,xdg/reflector,udev/rules.d}
mkdir -p "${conf}/airootfs/etc/systemd/"{timesyncd,journald}.conf.d
mkdir -p "${conf}/airootfs/etc/systemd/"{zram-generator,system}.conf.d
mkdir -p "${conf}/airootfs/etc/systemd/system/multi-user.target.wants"
mkdir -p "${conf}/airootfs/usr/local/bin"

cp "${path}/zram.conf" \
  "${conf}/airootfs/etc/systemd/zram-generator.conf.d"
cp "${path}/packages.x86_64" "${conf}"
cp "${path}/25-wireless.network" "${conf}/airootfs/etc/systemd/network"
cp "${path}/60-io.rules" "${conf}/airootfs/etc/udev/rules.d"
cp "${path}/99-sysctl.conf" "${conf}/airootfs/etc/sysctl.d"
cp "${path}/ntp.conf" "${conf}/airootfs/etc/systemd/timesyncd.conf.d"
cp "${path}/reflector.conf" "${conf}/airootfs/etc/xdg/reflector"
cp "${path}/arch-install" "${conf}/airootfs/usr/local/bin"
cp "${path}/linux-zen.preset" "${conf}/airootfs/etc/mkinitcpio.d"

sed "s/NAME/${name}/" "${path}/profiledef.sh" > "${conf}/profiledef.sh"
cat "${path}/20-wired.network" \
  > "${conf}/airootfs/etc/systemd/network/20-ethernet.network"
cat "${path}/dns.conf" \
  > "${conf}/airootfs/etc/systemd/resolved.conf.d/archiso.conf"
cat "${path}/arch-zen.conf" \
  > "${conf}/efiboot/loader/entries/01-archiso-x86_64-linux.conf"
cat "${path}/pacman.conf" > "${conf}/pacman.conf"

cat << EOF > "${conf}/airootfs/etc/systemd/journal.conf.d/size.conf"
[Journal]
SystemMaxUse=512K
EOF

cat << EOF > "${conf}/airootfs/etc/systemd/system.conf.d/timeout.conf"
[Manager]
DefaultTimeoutStartSec=15s
DefaultTimeoutStopSec=2s
EOF

echo "$name" \
  > "${conf}/airootfs/etc/hostname"
echo 'editor no' \
  > "${conf}/efiboot/loader/loader.conf"
echo 'root:x:0:0:root:/root:/usr/bin/bash' \
  > "${conf}/airootfs/etc/passwd"
echo 'root::1::::::' \
  > "${conf}/airootfs/etc/shadow"

echo '- Building archiso...'
mkarchiso "${conf}"
