name: rls
on: workflow_dispatch
#  schedule:
#    - cron: "15 4 * * *"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Building
       run: |
         docker pull archlinux
         docker run --name archiso -dt --tmpfs '/build:noatime,size=4G,exec' --privileged archlinux:latest
         docker exec archiso ls /
         docker cp ./docker archiso:/
         docker exec archiso bash ./docker/main
         docker cp archiso:/out/archiso-v-x86_64.iso /dev/shm

     - name: Calculating the hash
       run: openssl sha256 /dev/shm/archiso-v-x86_64.iso  #| tee -a "${GITHUB_ENV}"

     - name: Releaseing
       run: |
         gh release delete iso --cleanup-tag -y || true
         gh release create iso /dev/shm/archiso-v-x86_64.iso
       env:
         GH_TOKEN: ${{ github.token }}
