name: rls
on:
  workflow_dispatch:
  schedule:
    - cron: "15 3 * * *"
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Building
       run: |
         docker pull archlinux:latest
         docker run --name archiso -dt --privileged archlinux:latest
         docker cp ./docker archiso:/
         docker exec archiso bash ./docker/main
         docker cp archiso:/out/archiso-v-x86_64.iso .
         docker stop archiso

     - name: SHA calculation
       run: echo "sha=$(openssl sha256 ./archiso-v-x86_64.iso | cut -d ' ' -f2)" | tee -a "${GITHUB_ENV}"

     - name: Releaseing
       run: |
         gh release delete iso --cleanup-tag -y || true
         echo "SHA256: \`${sha}\`" | gh release create iso ./archiso-v-x86_64.iso -F -
       env:
         GH_TOKEN: ${{ github.token }}
